BepInEx/BepInEx

BepInEx/ConfigWrapper.cs

Allows to avoid spamming GetValue in Update.

Added SettingChanged event to ConfigWrapper

---

BepInEx.Core/Bootstrap/BaseChainloader.cs
BepInEx.Core/Logging/DiskLogListener.cs

Adds log file limit to config so its easier for plugin devs to test stuff and fixes silent crash when starting >5 processes.

Add log file limit to config

---

BepInEx.IL2CPP/ProxyAssemblyGenerator.cs

Hash unity base libs so unhollowed assemblies get regenerated when base libs are changed.
Move base libs to `BepInEx/unity-libs` so `BepInEx/unhollowed` can be safely removed again.

Hash unity base libs and move them to BepInEx/unity-libs

---

BepInEx.Core/Contract/Attributes.cs

Fix BepInDependency cache NullReferenceException bug added with #152
- Bug fix (non-breaking change which fixes an issue)
- My code follows the code style of this project.

Fix BepInDependency cache

---

BepInEx.Core/Logging/StdOutLogListener.cs

Deduplicates the implementation of the event args formatting.
Maintenance++ and removes an allocation when the standard output stream is not set.

Deduplicate StdOutLogListener implementation

---

BepInEx.Core/Logging/Logger.cs

Avoids allocations as a side effect

Simplify logger source clear and remove

---

doorstop/run_bepinex.sh

Fixes for injecting into Linux processes. Each change is detailed in the commit message.
Linux support has been completely broken. This patch fixes it.
Related: #293 
Tested on One Step From Eden. Config files were successfully generated.
N/A
- N/A My change requires a change to the documentation.
- N/A I have updated the documentation accordingly.

Fix the Linux launcher script

---

BepInEx.Unity/ThreadingHelper.cs

A much more efficient extension for running work on multiple threads. Not sure if we're keeping ThreadingExtensions or not, but since it was already written then why not open a PR. Seems to work well from some limited tests.

Add ThreadingExtensions.ForEachParallel

---

BepInEx.IL2CPP/Hook/IL2CPPDetourMethodPatcher.cs

Adds a conversion for the managed bool type to a byte in the il2cpp to managed trampoline.
Fixes an issue with stack parameters being improperly read thus giving invalid boolean states in patches.

[Il2Cpp] Convert managed bool to byte in Native to Managed trampoline

---

BepInEx.IL2CPP/ProxyAssemblyGenerator.cs

Run basic AttributeRestoration for cpp2il

---

README.md
Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj

Bump Il2CppInterop

---

Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.AsmToCecilConverter.cs
Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
nuget.config

This pull request enables Bepinex to use the latest Cpp2IL.
The `new-analysis` branch is legacy, and support has only been held for Bepinex. Switching would allow full focus on the `development` branch.
It has not been tested, but similar code was used in AssetRipper.

Switch to the `development` branch of Cpp2IL

---

BepInEx/Bootstrap/Chainloader.cs

Fix logging "1 plugins to load" instead of "1 plugin to load"

---

BepInEx/Logging/Logger.cs

Adding or removing `Logger.Listeners` and `Logger.Sources` can cause exceptions if some other thread is currently enumerating these lists, e.g. when calling `Logger.Log`. This usually causes unexpected crashes in whatever code was trying to log something at an unfortunate time. I noticed it can also lead to a listener not getting some log messages.
The changes result in sending log events being slightly faster with no allocations (saves a few ms overall), but Add/Remove operations are slightly slower (still 0 ms overall).
Fixes #655

Make Logger.Listeners and Logger.Sources thread safe

---

Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
build/Program.cs

Bumps Il2CppInterop to `1.4.6-ci.389`
Bumps Dobby to `1.0.5`
Fixes #668

Bump Il2CppInterop & Dobby

---

Runtimes/Unity/BepInEx.Unity.Common/BepInEx.Unity.Common.csproj
Runtimes/Unity/BepInEx.Unity.Common/UnityInfo.cs
Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
Runtimes/Unity/BepInEx.Unity.Mono.Preloader/EntrypointPatcher.cs

Bumps Il2CppInterop to `1.4.6-ci.426`
Bumps Cpp2IL to `2022.1.0-development.972` (& accounts for the breaking changes)
Bumps Iced to `1.20.0`
Fixes #866

Bump Cpp2IL & Il2CppInterop

---

BepInEx.Core/BepInEx.Core.csproj
BepInEx.Preloader.Core/BepInEx.Preloader.Core.csproj
README.md
Runtimes/NET/BepInEx.NET.Common/BepInEx.NET.Common.csproj
Runtimes/NET/BepInEx.NET.Framework.Launcher/BepInEx.NET.Framework.Launcher.csproj
Runtimes/Unity/BepInEx.Unity.Common/BepInEx.Unity.Common.csproj
Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
Runtimes/Unity/BepInEx.Unity.Mono.Preloader/BepInEx.Unity.Mono.Preloader.csproj
Runtimes/Unity/BepInEx.Unity.Mono/BepInEx.Unity.Mono.csproj

This pr does minor upgrades to some dependencies. They are non breaking.
For all 3 upgrades: they are non breaking bug fixes. The assetripper one in particular is required for old unity mono. It should be noted however that this alone isn't enough for old mono to work as legacy monomod still breaks on v6 due to a preloader crash.
I checked unity old mono, still works.

Upgrade Harmonyx, Iced and AssetRipper.Primitives packages

---

.github/workflows/build.yml
.github/workflows/build_pr.yml

Upgrade the workflows sdks so they can build with newer C# features that the net6.0 tfm still supports.
To get features such as collection expression to work.
It was already building in net8 sdk locally.

Upgrade the github workflows sdk to 8.0.x

---

README.md
build.cake

Upgrade Doorstop to include crash fix for old unity versions.
Tested bepin build in various unity versions, no regressions.

Upgrade Doorstop to version 4.4.0

---

Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs

Package update, works fine in previously working games.

v6 - Bump Il2CppInterop to 1.5.0-ci.620
