- BepInEx/Bootstrap/AssemblyPatcher.cs
- BepInEx/Bootstrap/Chainloader.cs
- BepInEx/Logging/UnityLogWriter.cs
* Add opt-in logging for Unity messages via `log_unity_messages` configuration option
* Fix assembly dumping to only dump patched assemblies
> Add logging for Unity messages and fix assembly dumping

- BepInEx/BepInEx.csproj
- BepInEx/Bootstrap/Preloader.cs
- BepInEx/Bootstrap/PreloaderPatchManager.cs
Fix BepInEx assemblies being resolved by mono instead of the custom assembly resolver.
This is done because Mono is not capable of properly handling paths with "exotic" characters.  
As a result, if the game path contained, say, symbols from Japanese or Russian alphabets, Mono would fail to resolve `Mono.Cecil.dll` that is located in the same folder as `BepInEx.dll` and that is needed to run the preloader at all.
As a tradeoff, the path to `BepInEx\core` is now hard coded as `{GameDirectory}\BepInEx\core`. This should be fine in the case of this framework.
> Fix uncontrolled assembly resolving

- BepInEx/Logging/UnityLogWriter.cs
Prevents unnecessary message popups in interface.
> Mark unity Log messages as Info instead of Message

- BepInEx/Logging/UnityLogWriter.cs
Implement suggestion in #53 by explicitly writing to Unity log when the log level is too low.
> Display all log levels in output_log.txt

- BepInEx.Preloader/Patching/AssemblyPatcher.cs
Added two configuration options under `Preloader` section:
`LoadDumpedAssemblies`: If enabled, BepInEx will load patched assemblies from BepInEx/DumpedAssemblies instead of memory. This can be used to be able to load patched assemblies into debuggers like dnSpy. If set to true, will override DumpAssemblies.
`BreakBeforeLoadAssemblies`: If enabled, BepInEx will call Debugger.Break() once before loading patched assemblies. This can be used with debuggers like dnSpy to install breakpoints into patched assemblies before they are loaded.
> Add config options to enable debug patched assemblies with dnSpy

- BepInEx/Bootstrap/Chainloader.cs
- BepInEx/Contract/Attributes.cs
- BepInEx/Contract/PluginInfo.cs
- BepInEx/Utility.cs
Plugins can require a minimum version of another plugin. 
Exposed DependencyErrors is for displaying ton screen in MessageCenter so average user can see something is wrong.
>  Added MinimumVersion support to BepInDependency and added BepInIncompatibility

- BepInEx/ConsoleUtil/Kon.cs
Currently, BepInEx fails to run under Linux/OSX due to the missing externs. It crashes whenever Console is called.
This small change allows Linux/OSX to be able to run BepInEx without issues by disabling the Console.
This is a bandaid to the problem, Console is only supported under
Windows OS.
> Allow Console to fail gracefully if missing extern

- BepInEx.Patcher/BepInEx.Patcher.csproj
- BepInEx.Preloader/BepInEx.Preloader.csproj
- BepInEx/BepInEx.csproj
This change will make sure that NuGet packages are always resolved from the solution root directory. It redoes what [8cf0a42](https://github.com/BepInEx/BepInEx/commit/8cf0a425942f8df852082a13ce5967b64d8000f8) did, which got reverted by [22e34c3](https://github.com/BepInEx/BepInEx/commit/22e34c3456beab9d6f25843b4ef4dc0cecf51ba7).
> Resolve NuGet packages folder relative to current solution dir

- BepInEx/Configuration/ConfigFile.cs
Limiting the line.Split in Reload() to 2 substrings to allow for values containing `=` characters. Original functionality is maintained.
I stumbled across this bug when trying to use `=` characters in my config values.  
I see no reason config values shouldn't be allowed to contain `=`'s, I assume this was an oversight when originally implemented. 
This is such a small, basic change that I have not tested it but if absolutely necessary I can test it.
> Limit line.Split in ConfigFile.Reload()

- BepInEx.Core/Bootstrap/BaseChainloader.cs
Stops
https://github.com/BepInEx/BepInEx/blob/5bababd7a3158f63f94c57d3fb712f05c2d621bd/BepInEx.Core/Bootstrap/BaseChainloader.cs#L127-L129
from appearing everytime.
> Fix "wrong version of BepInEx" warning caused by dll split in v6

- BepInEx.Bootstrap/BepInEx.Bootstrap.csproj
- BepInEx.Core/BepInEx.Core.csproj
- BepInEx.Core/Console/Windows/Kon.cs
- BepInEx.IL2CPP/BepInEx.IL2CPP.csproj
- BepInEx.IL2CPP/ProxyAssemblyGenerator.cs
- BepInEx.Patcher/BepInEx.Patcher.csproj
- BepInEx.Preloader.Core/BepInEx.Preloader.Core.csproj
- BepInEx.Preloader.Unity/BepInEx.Preloader.Unity.csproj
- BepInEx.Unity/BepInEx.Unity.csproj
- BepInExTests/BepInExTests.csproj
- BepInExTests/TrampolineTests.cs
- build.cake
Changes Il2Cpp builds to now target .NET Standard 2.1.
This change migrates `BepInEx.IL2CPP` core to .NET Standard 2.1. To support this, `BepInEx.Core` and `BepInEx.Preloader.Core` were updated to build both net35 and netstandard2.1 targets. In addition, `BepInExTests` was updated to target netcoreapp3.1 to facilitate the change.
The code in `BepInEx.IL2CPP` was updated to not rely on `AppDomain` API directly as it is missing from .NET Standard 2.1 (but is present in mono). This was deemed fine as it was the only necessary change.
Finally, the build output was restructured: because core libraries now have multiple TFMs, they are now output into `bin/Core/<TFM>` folder. This change does not affect `IL2CPP` and `Unity` folders which are the actual build output (and which are used in CI). …
> WIP: Port Il2Cpp builds to .NET Standard 2.1

- BepInEx.Core/Configuration/ConfigFile.cs
Preserves exception compatibility and behaves better, including
having improved codegen as a result.
See https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYYCmAbqQHYAu6AopbQBICGVwANqQE6ZQUA3IWIiiaTABZ0AOQD2NAJYAzAJ4AKAJRj8O4umVyepVgGMAFunWNqNNh248APNgB86CukVV+FAHQA4qQ0AJJU5HKmrEpyVAAyigDONFqaukj6mcT+YREA1qTqNOZJADToVACunJyawhlZ6AC+Oi1ITUA==
Switched LINQ Cast call into a compiler introduced cast. It's faster and behaves identically.
- [*] My code follows the code style of this project.
> Avoid LINQ call by using the expected type in the foreach loop

- BepInEx/Bootstrap/Chainloader.cs
- BepInEx/ThreadingHelper.cs
To prevent forceful destruction of the manager GOs by the game (see Oddworld: Soulstorm) via
`Resources.UnloadUnusedAssets` we can use https://docs.unity3d.com/ScriptReference/HideFlags.HideAndDontSave.html
Oddworld: Soulstorm (for example) uses aggressive resource management approach that forcefully unloads any objects, including those that were set to DontDestroyOnLoad(). There are 3 possible workarounds:
1. Move away from GameObjects (unlikely, breaking)
2. Use custom loaders for specific game that will patch game's code (unlikely, not relevant to Bepin itself)
3. Resort to easier solution via custom object flags that will prevent it from being unloaded.
Preliminary testing on ` Oddworld: Soulstorm` (custom build of Unity 2019.4.12) for about an hour. Plugins used to be destroyed and …
> Update Bepin GOs to use HideAndDontSave flags

- BepInEx.Core/Configuration/ConfigFile.cs
- BepInEx.Core/Console/Windows/WindowsConsoleDriver.cs
- BepInEx.Core/Logging/DiskLogListener.cs
- BepInEx.Core/Utility.cs
Disables the byte order mark (BOM) from the UTF-8 encoding instances used to write to config files and log files. `WindowsConsoleDriver` uses pure UTF-8 as well, so I also adjusted it to reuse the same encoding instance as the others.
I also have another branch on my fork called `v5/remove-utf8-bom` in case this one is merged and you want to backport it.
Discord recently introduced a feature that allowed for previewing text files without downloading them, but this never seems to work on log files. Upon further examination, it was because the files were equipped with a BOM.
I did further research and found that nobody argued in favor of UTF-8 BOM. The technical reason for this is that the BOM provides endianness information. However, UTF-8 uses singular bytes (instead of 4 or 2 bytes, like …
> Remove BOM from UTF-8 File Encodings

- BepInEx.IL2CPP/IL2CPPChainloader.cs
- BepInEx.IL2CPP/Preloader.cs
Fixed issue #229.
* Now we manually parse the first three components of the version.
* Now we can override the version in the config file: `[Unity] Version = 2019.4.16`
* Moved version initialization to Preloader to avoid confusion in the logs.
> Issue #229 fix

- BepInEx.IL2CPP/BepInEx.IL2CPP.csproj
- BepInEx.IL2CPP/ProxyAssemblyGenerator.cs
Makes Il2CppAssemblyUnhollower (https://github.com/BepInEx/Il2CppAssemblyUnhollower/pull/3) use Il2cppDumper's (https://github.com/BepInEx/Il2CppDumper/pull/2) dummy dlls directly instead of relying on file system (which is slower, prone to file locks and redundant)
> Use Il2CppDumper dummy assemblies directly

- BepInEx.IL2CPP/Preloader.cs
- BepInEx.IL2CPP/ProxyAssemblyGenerator.cs
> Add automatic downloading of unity base libraries

- BepInEx.Preloader/Preloader.cs
Adds logging for game version (last modification time) and logs the preloader patcher being added.
Adds two extra tidbits of information for logging:
* The last time the executable was modified
* That the preloader patcher has been loaded.
Detecting which version of a game is ran helps people running technical support for BepInEx distributions to identify what support needs to be provided.
The default logging does not state it adds the preloader patcher, but then does count it in the total patchers loaded, confusing end users.
```
[Message:   BepInEx] BepInEx 5.4.9.0 - Risk of Rain 2 (02/05/2020 13:50:22)
[Info   :   BepInEx] Running under Unity v2018.4.16.15133130
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] …
```
> Extend bootup info logging

- BepInEx.Core/Bootstrap/BaseChainloader.cs
- BepInEx.Preloader.Core/Patching/AssemblyPatcher.cs
Currently stacktraces are logged with Debug log level which is not enabled by default making logs sent by users useless, this fixes it
> Make stacktraces Error instead of Debug

- BepInEx.IL2CPP/Utils/Collections/Il2CppManagedEnumerator.cs
Due to the nature of unhollower, ienumerators which were compiler generated and not explcitly defined inherit from il2cppobjectbase and thus are not handled by the current Il2CppManagedIEnumerator. This change adds support for this
Added an additional case to the current property in Il2CppManagedIEnumerator
It allows for returning non explicitly defined IEnumertors which may be useful if the game implements a routine you would like to use
Tested in Among Us (Unity v2020.3.7) and appears to function as expected
> Support returning Il2Cpp IEnumerators which had been compiler generated

- build.cake
The current wording on the download page states that the architecture of the OS (32 or
64-bit) is leading for which version of BepInEx to download. This
however should be the architecture for which the game is built, as you
can run 32-bit Windows games on 64-bit Windows systems and need the
32-bit version of BepInEx in this case.
I helped an user today who was very confused about why his installation of BepInEx for a 32-bit game was not working. He used 64-bit Windows, so he downloaded the 64-bit version as instructed by the download page. It took a few attempts to convince him to download the 32-bit version. This hopefully reduces the amount of new souls that download the wrong version.
This has not been tested, as I don't have access to the CI environment. I hope that editing the …
> CI: Emphasize architecture of game instead of OS

- BepInEx.IL2CPP/Hook/IL2CPPDetourMethodPatcher.cs
Replaces the old INativeMethodInfoStruct.StructSize with UnityVersionHandler.MethodSize().
INativeMethodInfoStruct.StructSize is planned to be removed in a future update of unhollower in favor of UnityVersionHandler's size providers.
> [Il2Cpp] Use UnityVersionHandler's Size Providers in Harmony Backend

- BepInEx.Core/Configuration/ConfigEntryBase.cs
I added `protected` to the access modifiers for the `ConfigEntryBase` constructor
This allows for an external assembly to create a type that extends off of `ConfigEntryBase`
Currently, the only constructor is `internal`, which prevents an external assembly from creating a class that derives from it
I built the project in both debug and release mode.
I replaced the existing `BepInEx.Core.dll` in my install with a new one
Everything seemed normal
> Change visibility of ConfigEntryBase constructor to `internal protected` to allow for external implementations

- README.md
Change the "Bleeding Edge builds" link in the readme to point to `builds.bepinex.dev` instead of `builds.bepis.io`
`builds.bepis.io` no longer responds as of 15/5/22
I clicked on the link
My testing environment: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0`
> Update bleeding edge builds link to newer domain

- BepInEx.Core/Bootstrap/BaseChainloader.cs
- Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs
Adds events to chainloader to allow for library plugins to make apis like [PluginSingleton](https://github.com/NuclearPowered/Reactor/blob/master/Reactor/PluginSingleton.cs) or [RegisterCustomRpcAttribute](https://github.com/NuclearPowered/Reactor/blob/master/Reactor/RegisterCustomRpcAttribute.cs)
> Add chainloader events

- Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
Adds a config option for disabling xref so you can do it as a temporary workaround when xref causes crashes.
Also disables xref on x32 by default because its very flaky and doesn't provide correct results there anyway, it could be enabled again if its ever fixed properly on il2cppinterop side.
> Add a config option to disable xref and disable it by default on x32

- doorstop/run_bepinex.sh
Allows the modded game to be ran with parameters from launcher level.
basically it allows to do something like this:
`/bin/sh "/pat/to/game/directory/run_bepinex.sh" "" "-screen-width 1000"` after setting cwd to game directory.
... this `""` works like skipping argument for game executable AND doesn't appear in $@ from game point of view
I am rewriting CastleStory launcher and figured out that this is most likely a mistake in run_bepinex, I don't want to update to 6.x yet - it is fixed there tho (at least looks like so).
I've just run the game from command line and by spawning process from launcher.
- [?] My change requires a change to the documentation.
- [?] I have updated the documentation accordingly.
(I can update docs if it is needed ^^)
> fix: handle parameter spread for lts version

- README.md
- Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
Bumps Il2CppInterop from v1.4.1 to v1.4.4
The current version used by BepInEx is behind on multiple bugfixes that allow newer unity games to run.
> Bump Il2CppInterop to v1.4.4

- README.md
- Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
Bumps Il2CppInterop from v1.4.4 to v1.4.5
A few bug fixes were added in the new version that fix issues on newer unity games and allow for generic method patching.
> Bump Il2CppInterop to v1.4.5

- BepInEx.Preloader.Core/PlatformUtils.cs
Wine can have versions like `8.0-rc5` which currently crash, we only get it to log it for debugging so just don't try to parse it.
> Don't try to parse the wine version

- Runtimes/Unity/Doorstop/run_bepinex_il2cpp.sh
- Runtimes/Unity/Doorstop/run_bepinex_mono.sh
Resolves a recent change (I think) with how Steam on Linux launches applications. I believe the extra `--` arguments are messing up the argument counts for the relaunch. Using the following change I was able to get the game working. Basically added 2 extra arguments and shifted the last argument by 2.
```
if [ "$2" = "SteamLaunch" ]; then
steam="$1 $2 $3 $4 $5 $6 $0 $7"
shift 7
$steam "$@"
exit
fi
```
This PR resolves issue #559. See also #562 for the same change on `v5-lts` branch.
I tested this change using the game Ultimate Chicken Horse on Steam on a laptop running Fedora 37.
> Fix argument count when launched with Steam on Linux

- Runtimes/Unity/BepInEx.Unity.IL2CPP/Utils/Il2CppUtils.cs
For some reason the manager GameObject has no name set, so it appears as "New Game Object" whenever a plugin uses `BasePlugin.AddComponent`.
In BepInEx 5 and older it was always named "BepInEx_Manager", so I think this is a bug.
Tested, works fine.
> Fix manager GameObject not having a name

- Runtimes/Unity/Doorstop/run_bepinex_il2cpp.sh
- Runtimes/Unity/Doorstop/run_bepinex_mono.sh
This targets master. v5-lts version: #693
This modifies `run_bepinex*.sh` to support both old and new versions of Steam, as well as to support paths that contain spaces (which were supported in v5-lts but not in master).
An additional, simple fix for a generic shell-script issue is also included.
Recently, Steam apparently changed the way it executes the game, inserting `--` arguments where they didn’t exist before. So #562 and #563 modified `run_bepinex*.sh` to match this change by hardcoding the two added arguments. As noted in https://github.com/BepInEx/BepInEx/pull/562#pullrequestreview-1548351028, this presumably made it impossible to run BepInEx in older versions of Steam.
This pull request teaches the code in `run_bepinex*.sh` to handle the `--` arguments in a special way, …
> run_bepinex*.sh: self-relaunch improvements

- doorstop/run_bepinex.sh
Same as #692 but branched from v5-lts.
This modifies `run_bepinex.sh` to support both old and new versions of Steam, as well as to support 
additional arguments beyond `$5`/`$7` (which were supported in master but not in v5-lts).
An additional, simple fix for a generic shell-script issue is also included.
Recently, Steam apparently changed the way it executes the game, inserting `--` arguments where they didn’t exist before. So #562 and #563 modified `run_bepinex*.sh` to match this change by hardcoding the two added arguments. As noted in https://github.com/BepInEx/BepInEx/pull/562#pullrequestreview-1548351028, this presumably made it impossible to run BepInEx in older versions of Steam.
This pull request teaches the code in `run_bepinex.sh` to handle the `--` arguments in a special way, …
> v5 run_bepinex.sh: self-relaunch improvements

- README.md
- build.cake
- doorstop/doorstop_config.ini
- doorstop/run_bepinex.sh
This upgrades Doorstop to version 4.2.0 which notably fixes a regression that was found with the 5.4.23 released version of bepinex where it couldn't hook its own assembly loading which prevented to shim Bepinex.Harmony when needed by legacy plugins.
It fixes the regression found with the 5.4.23 release
I already tested doorstop on both windows and linux and confirmed the build system correctly downloaded a version that fixed the regression.
> Upgrade Doorstop to version 4.2.0

- README.md
- Runtimes/Unity/Doorstop/doorstop_config_mono.ini
- Runtimes/Unity/Doorstop/run_bepinex_mono.sh
- build/Program.cs
This upgrades bepinex (master) to use Doorstop version 4.2.0 with equivalent defaults regarding the mono search paths changes
It fixes minor issues and improves the flexibility regarding the mono search path.
I haven't tested much besides the fact that it compiles (I am not familiar with v6 enough)
> Upgrade doorstop to version 4.2.0 (v6)

- README.md
- Runtimes/Unity/Doorstop/doorstop_config_il2cpp.ini
- Runtimes/Unity/Doorstop/doorstop_config_mono.ini
- Runtimes/Unity/Doorstop/run_bepinex_il2cpp.sh
- Runtimes/Unity/Doorstop/run_bepinex_mono.sh
- build/Program.cs
Upgrade Doorstop to version 4.3.0. This fixes a regression from v5 where dnspy debugging broke on old mono. By the same token, it adds 2 features:
- It is now possible to redirect the untiy's boot.config file
- Doorstop debugging now works on old mono and dnspy debugging no longer requires a patched mono even if it is an old mono.
It fixes a regression from v5 where dnspy debugging broke on old mono and adds 2 interesting features that the new version of doorstop offers.
I tested that the build system correctly obtained the new doorstop on all builds and tested in a unity 2018.4.12 game with 2 versions (one that released with old mono and another that released with new mono).
> Upgrade Doorstop to 4.3.0 (v6)

- README.md
- build.cake
- doorstop/doorstop_config.ini
- doorstop/run_bepinex.sh
Upgrade Doorstop to version 4.3.0. This fixes a regression where dnspy debugging broke on old mono. By the same token, it adds 2 features:
- It is now possible to redirect the untiy's boot.config file
- Doorstop debugging now works on old mono and dnspy debugging no longer requires a patched mono even if it is an old mono.
It fixes a regression where dnspy debugging broke on old mono and adds 2 interesting features that the new version of doorstop offers.
I tested that the build system correctly obtained the new doorstop on all builds and tested in a unity 2018.4.12 game with 2 versions (one that released with old mono and another that released with new mono).
> Upgrade Doorstop to version 4.3.0 (v5)

- BepInEx.Core/BepInEx.Core.csproj
- BepInEx.Preloader.Core/BepInEx.Preloader.Core.csproj
- README.md
- Runtimes/Unity/BepInEx.Unity.Common/BepInEx.Unity.Common.csproj
- Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
This simply upgrades the MonoMod version to the latest legacy one available which is non breaking, but allows to get a very important bugfix that has been preventing to boot old mono unity games (unity 5.x, 2017.x by default and optionally available in 2018.1-2019.1).
Currently, attempting to boot would yield this issue that has been documented before: https://github.com/MonoMod/MonoMod.Common/pull/23 . Essentially, a preloader crash happens due to an NRE in MonoMod's ReflectionHelper's cctor. It appears the issue was found and actually merged which was a simple fix by adding a `?` null check.
After investigation, the ONLY version of MonoMod legacy that includes this fix is 22.7.31.1 which is the last release of the legacy branch. This pr allows old mono games to boot due to this upgrade. …
> Upgrade MonoMod to 22.7.31.1 to fix old mono preloader crashes

- Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
Bumps Cpp2IL to the latest prerelease (18). ~~It isn't on nuget, so the new package reference points to the corresponding CI build on [nuget.samboy.dev](nuget.samboy.dev).~~
The currently used version doesn't have support for metadata version 29.2 (Unity 2023.2+) and 31 (2022.3.33+). From the discord server: https://discord.com/channels/623153565053222947/754333645199900723/1277435800153358457
~~It hasn't, which is why this PR is currently a draft.~~
> Bump Cpp2IL

- BepInEx.Core/Paths.cs
- Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
Any Unity game can have its _Data folder renamed to just `Data` and continue working just fine. The issue is BepInEx assumes that there is always a game name prefix, which causes a startup crash.
Closes #974
Tested locally on a game with a bunch of plugins already installed. Renamed data folder to `Data` and tried to regenerate interop assemblies, which crashed on master but worked fine on this PR.
> Fix failing to initialize if game's Data folder is just 'Data'

- Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs
- Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
Assemblies are often loaded on the il2cpp side but not on the mono side, causing confusion when using reflection.
This will load all interop assemblies right before plugins are loaded, which should mostly avoid these issues at a low time cost of around 40ms.
> Automatically load all interop assemblies before loading plugins

- Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
Instead of hardcoding the metadata path expose it in config.
Turns out this is super convenient to have when having to mess with metadata files. Don't have to edit bepinex for every change and it's possible to relocate decoded files into the bepinex directory to keep it self-contained.
Tested for regressions by updating existing installs and in new installs with relocated metadata.
> Add GlobalMetadataPath setting

- BepInEx.PatcherProvider/BepInExPatcherProvider.cs
- BepInEx.PluginProvider/BepInExPluginProvider.cs
Change the behaviors of the default providers so if multiple assemblies with the same name exists, but in different directories, ignore any that are located deeper.
This fixes a problem where duplicate keys gets added to the dictionary because the file name without extensions is the same. In this situation, the path that is the shallowest should win over the deeper ones. This resolves this ambiguity.
I tested by placing the same assembly file names in the plugins directory, but one of them was 2 directories deeper. Testing shows it correctly picks the one at the root of the plugin folder instead of the one under the 2 directories.
> Prioritize the shallowest path for the same assembly name in the default providers

- BepInEx.Core/Logging/Logger.cs
- BepInEx.Preloader.Core/Logging/ChainloaderLogHelper.cs
- Runtimes/Unity/BepInEx.Unity.Mono.Preloader/UnityPreloaderRunner.cs
- Runtimes/Unity/BepInEx.Unity.Mono/BepInEx.Unity.Mono.csproj
- Runtimes/Unity/BepInEx.Unity.Mono/Configuration/KeyboardShortcut.cs
- Runtimes/Unity/BepInEx.Unity.Mono/UnityInput.cs
- Runtimes/Unity/BepInEx.Unity.Mono/UnityTomlTypeConverters.cs
- Runtimes/Unity/Doorstop/run_bepinex_il2cpp.sh
- Runtimes/Unity/Doorstop/run_bepinex_mono.sh
This PR backports all relevant features I could see were missing from master/v7-dev that originated in v5. It includes:
- Add a specific error in the bash doorstop scripts when trying to launch an exe
- ~~Add an option to disable the HideAndDontSave flag (unlike v5, this is true by default since it's generally a more sensible default, but it's possible plugins or games might not work well with it)~~ EDIT: it was later decided to remove this because its inclusion is in doubts
- Print the last write time of the game's executable
- Add harmony and monomod to the preload list for unity mono
- Add UnityEngine.Rect to the TOML converters
- Make Logger.Listeners and Logger.Source thread safe
- Add a unity input abstraction layer for games with Input disabled
More information on where I took …
> v6: Backports features from v5

- BepInEx.Core/Bootstrap/TypeLoader.cs
When reading plugins assembly streams, it's not possible for the default providers to know without reading the assembly if it's a native dll or not. However, if it is a native dll, exceptions would bubble up to stall the entire loading process which shouldn't happen. This PR catches the exception.
This fixes a regression where having a native dll would cause a stray exception throw.
I tested on a unity 2018.4 game (new mono) and it fixed the issue.
> v7: Catch BadImageFormatExceptions when reading an assembly stream

- Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
This allows downloading the archive manually to unity-libs folder so that if the game is blocked by firewall, it won't throw an exception.
Perhaps another solution is to prompt the user to download from the default web browser but for now this fixes the problem for me and is easy to code (coded this ages ago, I don't even remember when).
I block all outbounds by default so naturally none of the games can connect to the internet.
fresh game folder with 2019.4.11.f Unity
download 2019.4.11.zip to `BepInEx\unity-libs`
copy files from `bin\Unity.IL2CPP` to `BepInEx\core`
copy, from release, the dotnet runtime and everything outside BepInEx to '.\', and dobby.dll to  `BepInEx\core`
run the game once, see the archive decompressed with no more HTTP exception
- [x ] New feature (non-breaking …
> Checks if target Unity binaries archive exists before attempting download in case game's network conenction is blocked

- build/Build.csproj
Fixes CI broken by net6.0 being deprecated.
> Switch Build.csproj TargetFramework to net8.0

- Runtimes/Unity/BepInEx.Unity.IL2CPP/BepInEx.Unity.IL2CPP.csproj
Needed to support the latest Unity engine versions. Tested in a few games, works with no apparent regressions.
> v6 - Bump Cpp2IL to pre-release.19
